# Generated by Django 3.2.8 on 2021-10-08 07:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import colorfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('date_added',
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name='Дата добовления')),
            ],
            options={
                'verbose_name': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='IngredientList',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('date_added',
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name='Дата добовления')),
            ],
            options={
                'verbose_name': 'Списко ингирдиентов',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name',
                 models.CharField(max_length=200,
                                  verbose_name='Название')),
                ('measurement_unit',
                 models.CharField(max_length=25,
                                  verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': ('Ингридиент',),
                'verbose_name_plural': 'Ингридиенты',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='IngredientsInRecipes',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('amount_of_ingredients',
                 models.PositiveSmallIntegerField(default=1,
                                                  validators=[django.core.validators.MinValueValidator(1)],
                                                  verbose_name='Количество ингридиента')),
            ],
            options={
                'verbose_name': 'Ингредиент в рецепте',
                'verbose_name_plural': 'Нигридиенты в рецепте',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Фото блюда')),
                ('text', models.TextField(help_text='Заполните описание рецепта', verbose_name='Описание')),
                ('cooking_time',
                 models.PositiveSmallIntegerField(default=1,
                                                  help_text='Введите время приготовления в минутах',
                                                  validators=[django.core.validators.MinValueValidator(1)],
                                                  verbose_name='Время приготовления')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название категории')),
                ('color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальный идентификатор тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='RecipesTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='recipes.recipe',
                                   verbose_name='Рецепт')),
                ('tag',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='recipes.tag', verbose_name='Тег')),
            ],
        ),
    ]
