# Generated by Django 3.2.8 on 2021-10-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211008_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipes',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_recipe', to='recipes.ingredients', verbose_name='Ингредиент'),
        ),
    ]
