# Generated by Django 3.2.8 on 2021-10-10 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredientsinrecipes_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsinrecipes',
            old_name='amount_of_ingredients',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='ingredientsinrecipes',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients_recipe', to='recipes.ingredients', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientsinrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.IngredientsInRecipes', to='recipes.Ingredients', verbose_name='Ингридиент'),
        ),
    ]
