# Generated by Django 3.2.8 on 2021-10-15 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20211015_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientsInRecipes',
            new_name='IngredientInRecipe',
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Теги рецепта'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tag', through='recipes.RecipeTag', to='recipes.Tag', verbose_name='тег'),
        ),
        migrations.AddConstraint(
            model_name='recipetag',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='unique_tag'),
        ),
    ]
