# Generated by Django 3.2.8 on 2021-10-16 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_auto_20211016_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_list_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
