# Generated by Django 3.2.8 on 2021-10-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_ingredientlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='back_media/', verbose_name='Фото блюда'),
        ),
    ]
