# Generated by Django 3.2.8 on 2021-10-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribtion',
            new_name='Subscriptions',
        ),
    ]
