# Generated by Django 3.2.8 on 2021-10-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_subscriptions_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-pk',), 'verbose_name': 'Подписки'},
        ),
    ]
